# APP NAME
spring.application.name=sentinel-vault

# MYSQL CONNECTION
spring.datasource.url=jdbc:mysql://localhost:3306/sentinel_vault
spring.datasource.username=root
spring.datasource.password=root1234

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SERVER PORT
server.port=8080