# APP NAME
spring.application.name=sentinel-vault

# MYSQL CONNECTION
spring.datasource.url=jdbc:mysql://acela.proxy.rlwy.net:37076/railway
spring.datasource.username=root
spring.datasource.password=IsIXplyvJmJVTiVaBAYAUOBhQjYGJvlm  

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SERVER PORT
server.port=8080